#!/bin/bash
#SBATCH -N 8
#SBATCH --ntasks-per-node=16
#SBATCH -n 128
#SBATCH --exclusive
#SBATCH --time=24:00:00 
#SBATCH -J 3000mJ0
#SBATCH -o MITgcm.%J.out
#mail me when finished                                            
#SBATCH --mail-type=END                                           
#SBATCH --mail-user=h.burns@noc.soton.ac.uk 
source /etc/profile.d/modules.sh
module purge
module load shared
module load intel/compiler/64/14.0/2013_sp1.2.144
module load openmpi/intel/64/1.6.5
module load slurm/2.5.7
module load hdf5_18/1.8.11
module load netcdf/intel/64/4.3.0
module list
#
export SLURM_CPU_BIND="verbose"
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/jeff/packages/netcdf4/netcdf-fortran-4.2/mobilis/intel14.0/lib
echo "PATH"
echo $PATH
echo "LD_LIBRARY_PATH"
echo $LD_LIBRARY_PATH
echo "SLURM_NNODES"
echo $SLURM_NNODES
echo "SLURM_NODELIST"
echo $SLURM_NODELIST

#cd $PBS_O_WORKDIR
echo Directory is `pwd`
echo "Running on hosts: $SLURM_NODELIST"
echo "Running on $SLURM_NNODES nodes."
echo "Running on $SLURM_NPROCS processors."
echo Time is `date`
echo "MITgcm job starting"
date
echo "-----------------------------"
#limit coredumpsize 0
ulimit -s 1638400

echo "Running mpirun ./mitgcmuv >& socn.output"
./next_files/next0
mpirun -np 128 --mca mpi_paffinity_alone 1 ./mitgcmuv >& socn.output

date
echo "-----------------------------"
echo "MITgcm job finished"

exit

